### ISSUE TITLE
[Feature request] implement max-money config options

### ISSUE THREAD

**Issue by adamtomi** [YiC200333/XConomy#10]
I think this option would be useful for an economy plugin. I've switch from EssX economy to XConomy a couple of days ago, and so far so good, but i kinda miss this one feature. Could you please implement it at some point? Thanks <3

**Comment by YiC200333** [comment]
Ok, I will add this feature in the next version.

**Comment by adamtomi** [comment]
You're my hero :3

**Comment by YiC200333** [comment]
2.7.22 version is added this function
