### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by CJYKK** [YiC200333/XConomy#103]
您好，我有几个问题想请教一下。

1. 目前是否支持群组服使用数据库同步玩家余额（MySQL等）？
2. 是否考虑支持Velocity的Modern模式？

**Comment by YiC200333** [comment]
1、支持，使用MySQL同步效率会很慢，因为我没有做优化，推荐使用Redis同步
2、目前没有计划，可以使用Redis同步

**Comment by CJYKK** [comment]
> 1、支持，使用MySQL同步效率会很慢，因为我没有做优化，推荐使用Redis同步 2、目前没有计划，可以使用Redis同步

谢谢大佬~
