### ISSUE TITLE
mysql 同分流(转账)不见钱

### ISSUE THREAD

**Issue by hkkongou** [YiC200333/XConomy#104]
**Version of XConomy**  
XConomy-Bukkit-2.22.1

**Server version**  
purpur-1.20.1-2017

**Storage-type**  
MySQL

**Describe the issues**  
玩家在同一个分流pay另一个玩家，pay 显示已经转账，但是钱没有在另一个玩家的身上出现（消失了）

![image](https://github.com/YiC200333/XConomy/assets/61608872/61071652-be18-43fc-8782-7161175f3800)

这是伺服器的log
https://paste.denizenscript.com/View/112890

玩家都在同一个伺服器 (little_cute_cat)
mycowbay0626  打 /pay little_cute_cat

上面的截图显示xconomy 记录了玩家2次pay，第一次pay的话转帐了，第二pay的话金钱则没有变革

伺服器log的话就没有记录第一次的pay，只有第二的pay有纪录。

---

**(option)XConomy's config.yml**
https://paste.denizenscript.com/View/112889

**(option)Screenshots**

**Comment by hkkongou** [comment]
另一个案例，玩家在同一个分流里面什么都没有做，身上的金钱变少了
mariadb记录也没有找到任何金钱流动，伺服器log也没有

![image](https://github.com/YiC200333/XConomy/assets/61608872/56a723f4-f023-4ef8-b502-40cc46a3f9eb)

log:
https://paste.denizenscript.com/View/112891

**Comment by hkkongou** [comment]
好奇一问若果我想从mysql改redis的话该怎样汇入? (对这个问题有帮助吗)

**Comment by YiC200333** [comment]
你在bungeecord上安装了xconomy了吗？

**Comment by hkkongou** [comment]
> Reference in ne

原来bungee要安装的，我现在才知道，对不起
