### ISSUE TITLE
README文件中下载一栏GitHub后面没有 :

### ISSUE THREAD

**Issue by postyizhan** [YiC200333/XConomy#105]
**Version of XConomy**  
-

**Server version**  
-

**Storage-type**  
-

**Describe the issues**  
Issues

---

**(option)XConomy's config.yml**

**(option)Screenshots**
![{D8981DBE-1754-4011-9045-85C4841FB035}](https://github.com/YiC200333/XConomy/assets/97342038/1fd5e619-b4c4-4b0a-beb0-a75624395daa)

**Comment by YiC200333** [comment]
谢谢提醒
