### ISSUE TITLE
Powerboard display Money wrong, Placeholder.

### ISSUE THREAD

**Issue by TRC-Loop** [YiC200333/XConomy#106]
**Version of XConomy**  
XConomy V2.22.1

**Server version**  
Spigot 1.20.1

**Storage-type**  
SQLite / MySQL

**Describe the issues**  
Powerboard does not display the current Money,
when i use PlaceholderAPI:
%xconomy_balance% or formatted or value then it just shows 0.0 but i have 1000 on my balance.

---

**Comment by YiC200333** [comment]
try 2.24.4 version
