### ISSUE TITLE
v2.24.1 not working in PufferFish 1.20.1 (Paper Fork)

### ISSUE THREAD

**Issue by Aitooor** [YiC200333/XConomy#109]
**Version of XConomy**  
XConomy v2.24.1

**Server version**  
PufferFish 1.20.1
<img width="884" alt="Captura de pantalla 2023-08-15 a las 2 31 23" src="https://github.com/YiC200333/XConomy/assets/80640002/f4a3b340-e00e-4a72-9db4-d788ae3e4f42">

You can download here: https://pufferfish.host/downloads

**Storage-type**  
SQLite

**Describe the issues**  
You can see in the pastebin(on enable error): https://paste.md-5.net/qilojusoja.md

**Comment by Aitooor** [comment]
The same with Paper latest.

Version of XConomy
XConomy v2.24.1

Server version
Paper 1.20.1
<img width="870" alt="Captura de pantalla 2023-08-15 a las 2 36 10" src="https://github.com/YiC200333/XConomy/assets/80640002/cdd2d5fd-3f61-4b9a-99b1-6d422e49d1f7">

You can download here: https://papermc.io/downloads/paper

Storage-type
SQLite

Describe the issues
You can see in the pastebin(on enable error): https://paste.md-5.net/ozuquvikeq.md

**Comment by YiC200333** [comment]
Do you have CMI installed? Please modify the commands such as money, bal, balance, pay, and baltop within CMI / Alias to be set as false.

My test run is normal.
![image](https://github.com/YiC200333/XConomy/assets/38757441/2bb4e133-b72e-40a1-bb06-261cf50280d9)

**Comment by Aitooor** [comment]
No i don't use that. Buy i use RoyaleEconomy and in the latest version of XConomy there were not conflicts but with this ones breaks it. Thanks i think there are the aliases too, but i don't know but now is happening that. Thanks again :)
