### ISSUE TITLE
Update balance after edit database

### ISSUE THREAD

**Issue by krqteecho** [YiC200333/XConomy#110]
**Version of XConomy**  
XConomy V2.24.4

**Server version**  
Spigot 1.20

**Storage-type**  
MySQL

**Describe the issues**  
Issues

The balance does not change after changing it in the Database, only a restart helps. I would like it to be updated without restarting the player.

I use google translate so sorry for my english

**Comment by YiC200333** [comment]
XConomy has a caching mechanism, so you cannot directly modify the amount through the database. If you do not need caching, you can disable it in the configuration file. However, after disabling it, the load on the database will increase
