### ISSUE TITLE
V2.24.4 redis连接异常

### ISSUE THREAD

**Issue by Biliniko** [YiC200333/XConomy#113]
**Version of XConomy**  
XConomy V2.24.4

**Server version**  
Spigot 1.12.2（catserver）

**Storage-type**  
MySQL

**Describe the issues**  
使用redis连接会出现以下报错，使用2.24.1可以正常连接

> [20:10:33] [Server thread/INFO] [me.yic.xconomy.XConomy]: [XConomy] Redis连接异常
> [20:10:33] [Server thread/WARN] []: java.lang.NullPointerException
> [20:10:33] [Server thread/WARN] []: 	at me.yic.xconomy.utils.RedisConnection.getResource(RedisConnection.java:107)
> [20:10:33] [Server thread/WARN] []: 	at me.yic.xconomy.utils.RedisConnection.connectredis(RedisConnection.java:85)
> [20:10:33] [Server thread/WARN] []: 	at me.yic.xconomy.data.DataLink.create(DataLink.java:82)
> [20:10:33] [Server thread/WARN] []: 	at me.yic.xconomy.XConomy.onEnable(XConomy.java:103)
> [20:10:33] [Server thread/WARN] []: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> [20:10:33] [Server thread/WARN] []: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328)
> [20:10:33] [Server thread/WARN] []: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
> [20:10:33] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:438)
> [20:10:33] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384)
> [20:10:33] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:341)
> [20:10:33] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330)
> [20:10:33] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636)
> [20:10:33] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown 

---
使用redis5.0

**Comment by YiC200333** [comment]
多谢反馈，下个版本会修复
临时解决方案：给你的Redis服务器加个密码
#111

**Comment by Biliniko** [comment]
我有尝试添加密码，但是貌似登录参数出现了问题

> 21:02:50] [Server thread/INFO] [me.yic.xconomy.XConomy]: [XConomy] MySQL连接正常
> [21:02:51] [Server thread/WARN] [autosaveworld.core.AutoSaveWorld]: [AutoSaveWorld] Plugin XConomy attempted to establish connection socket://%5b0:0:0:0:0:0:0:1%5d:6379 in main server thread
> [21:02:53] [Server thread/WARN] [autosaveworld.core.AutoSaveWorld]: [AutoSaveWorld] Plugin XConomy attempted to establish connection socket://127.0.0.1:6379 in main server thread
> [21:02:53] [Server thread/INFO] [me.yic.xconomy.XConomy]: [XConomy] Redis连接异常
> [21:02:53] [Server thread/WARN] []: me.yic.xc_libs.redis.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'auth' command
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.Protocol.processError(Protocol.java:96)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.Protocol.process(Protocol.java:137)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.Protocol.read(Protocol.java:192)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.Connection.getStatusCodeReply(Connection.java:243)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.Connection.auth(Connection.java:377)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.Connection.initializeFromClientConfig(Connection.java:343)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.Connection.<init>(Connection.java:53)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.Jedis.<init>(Jedis.java:214)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.JedisFactory.makeObject(JedisFactory.java:181)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.pool2.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.pool2.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.pool2.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.util.Pool.getResource(Pool.java:34)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xc_libs.redis.jedis.JedisPool.getResource(JedisPool.java:373)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xconomy.utils.RedisConnection.getResource(RedisConnection.java:107)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xconomy.utils.RedisConnection.connectredis(RedisConnection.java:85)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xconomy.data.DataLink.create(DataLink.java:82)
> [21:02:53] [Server thread/WARN] []: 	at me.yic.xconomy.XConomy.onEnable(XConomy.java:103)
> [21:02:53] [Server thread/WARN] []: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> [21:02:53] [Server thread/WARN] []: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328)
> [21:02:53] [Server thread/WARN] []: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
> [21:02:53] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:438)
> [21:02:53] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384)
> [21:02:53] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:341)
> [21:02:53] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330)
> [21:02:53] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636)
> [21:02:53] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)

**Comment by YiC200333** [comment]
你试试2.25.1，2.25.1可以不用密码连接redis
