### ISSUE TITLE
Holograms not working with top 11-20 

### ISSUE THREAD

**Issue by UsefullSpoon** [YiC200333/XConomy#114]
**Version of XConomy**  
XConomy V2.25.1

**Server version**  
This server is running Paper version git-Paper-157 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 9cbad8e)

**Storage-type**  
SQLite 

**Describe the issues**  
Issues
Holograms do not want to show placeholders for Xconomy leaderboard above 10. 

---

**(option)XConomy's config.yml**
https://pastebin.com/CtHUiVT4

**(option)Screenshots**
![image](https://github.com/YiC200333/XConomy/assets/96959805/cc721e5c-08e1-4905-bfc4-938bd61b3710)

**Comment by YiC200333** [comment]
Current version only the top ten versions can be queried

**Comment by YiC200333** [comment]
try 2.25.5 version
