### ISSUE TITLE
add %xconomy_top_hide% + dynamic eco

### ISSUE THREAD

**Issue by xuandattnvn1995** [YiC200333/XConomy#115]
add %xconomy_top_hide% = true/false
balancetop display <player> => %xconomy_top_hide% = false
balancetop hide <player> => %xconomy_top_hide% = true
This helps me create a gui so players can hide/show their information on the top.
thank you!

add  dynamic eco.
%xconomy_dynamic%
%xconomy_dynamic_formatted%
![image](https://github.com/YiC200333/XConomy/assets/25878455/6f52ac9e-4f08-4d8d-ab52-223999a20f92)
When the player receives money from sources (mob/ah/shop...) the message +xxx money will appear for 2 seconds.
config.yml:
dynamic-eco:
      display-time: 2
      format: &e(+{amount})

**Comment by YiC200333** [comment]
These papi can ignore hidden player

%xconomy_top_player_#% indicate the player name of the ranking #
%xconomy_top_balance_#% indicate the player balance of ranking #
%xconomy_top_balance_value_#% indicate the player balance value of ranking #

**Comment by YiC200333** [comment]
dynamic eco can not be implemented through PAPI

**Comment by xuandattnvn1995** [comment]
> These papi can ignore hidden player
> 
> %xconomy_top_player_#% indicate the player name of the ranking # %xconomy_top_balance_#% indicate the player balance of ranking # %xconomy_top_balance_value_#% indicate the player balance value of ranking #

I mean you create papi %xconomy_top_hide% for hide top
if hiden =1 %xconomy_top_hide% = true
hiden = 0 %xconomy_top_hide% = false
![image](https://github.com/YiC200333/XConomy/assets/25878455/a93a9d2f-4f18-44a9-aefc-5b8ee0dda245)

I should be able to create the installation gui. If the player doesn't want them to appear on top, they will click and the console will execute the command
if %xconomy_top_hide% = true <=> hiden=1, use /balancetop display [name] 
if %xconomy_top_hide% = false <=> hiden=0, use /balancetop hide [name] 
![image](https://github.com/YiC200333/XConomy/assets/25878455/e910b782-dc81-4cae-aded-74d946e2787d)
![image](https://github.com/YiC200333/XConomy/assets/25878455/6246f84a-31c2-40ef-b8c0-b243dfc08595)

**Comment by xuandattnvn1995** [comment]
https://youtu.be/Er0FdicHeWw
deluxe menu:
![image](https://github.com/YiC200333/XConomy/assets/25878455/f624f236-0092-4b3c-891c-9f4750b745c0)

**Comment by YiC200333** [comment]
2.25.7 version added %xconomy_top_hidden%

**Comment by xuandattnvn1995** [comment]
![image](https://github.com/YiC200333/XConomy/assets/25878455/960cbe63-c24a-427a-961a-f08f5acb1869)
error:
The database hidden = 1 
but /papi parse LXD_VN %xconomy_top_hidden% = 0

**Comment by YiC200333** [comment]
2.25.8 version is fixed, try it
https://github.com/YiC200333/XConomy/releases/tag/2.25.8
