### ISSUE TITLE
Reboot command doesn't work

### ISSUE THREAD

**Issue by 1Pootis1** [YiC200333/XConomy#119]
**Version of XConomy**  
XConomy-Bukkit-2.25.7

**Server version**  
Paper 1.18.2

**Storage-type**  
SQLite

**Describe the issues**  
The reload command does not work, I write /xconomy reload, it says that it has restarted, but the chat messages remain unchanged, although I translated them in the configuration, or changed the name of the economy

---

**XConomy's config.yml** https://pastebin.com/dv66xbik

**Comment by YiC200333** [comment]
plese set Importdata-mode to false, Otherwise, no commands will take effect

**Comment by 1Pootis1** [comment]
It was set to false
