### ISSUE TITLE
Economic slowdown

### ISSUE THREAD

**Issue by 1Pootis1** [YiC200333/XConomy#120]
**Version of XConomy**  
XConomy-Bukkit-2.25.7

**Server version**  
Paper 1.18.2

**Storage-type**  
SQLite

**Describe the issues**  
When I turn on the server, I get this message: Essentials/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over {0}ms!
and so many times
![image](https://github.com/YiC200333/XConomy/assets/73141732/1df0a68f-01e8-4231-aa12-a071f4455e94)
I read that this may be related to the economy plugin and that it is slow, tell me how to fix this?

---

**XConomy's config.yml** https://pastebin.com/dv66xbik

**Comment by YiC200333** [comment]
After data import is completed, please turn off Importdata-mode

**Comment by 1Pootis1** [comment]
so it was turned off

**Comment by YiC200333** [comment]
If this problem still exists, you can set usepool to true in database.yml
