### ISSUE TITLE
和eco系列插件一起用时，eco的效果give_money不能用

### ISSUE THREAD

**Issue by tomhanksding** [YiC200333/XConomy#121]
**Version of XConomy**  
XConomy V2.25.7

**Server version**  
Spigot 1.20.1
**Storage-type**  
SQLite

**Describe the issues**  
Issues
和eco系列插件一起用时，eco的效果give_money不能用

---

**(option)XConomy's config.yml**

**(option)Screenshots**

**Comment by YiC200333** [comment]
xconomy不推荐和其他经济插件一起使用
