### ISSUE TITLE
Sending money sends the recieving player both messages

### ISSUE THREAD

**Issue by Time6628** [YiC200333/XConomy#122]
**Version of XConomy**  
XConomy V2.25.7

**Server version**  
spongeforge-1.16.5-36.2.5-8.2.1-RC1369

**Storage-type**  
MySQL

**Describe the issues**  
When using /eco give <player> <amount> the player the money is being sent to receives both messages about sending and receiving the money.
![javaw_2023-11-18_20-34-55](https://github.com/YiC200333/XConomy/assets/9041033/db7f4786-326a-4de1-a9f9-6d79eb9c267e)
The first message should be sent to the executor of the command, and the second message to the player.

**Comment by YiC200333** [comment]
I tested it on my own server and didn't find this issues.
