### ISSUE TITLE
Pay vanished players

### ISSUE THREAD

**Issue by MADS0LADEN** [YiC200333/XConomy#125]
**Version of XConomy**  
XConomy V2.25.7

**Server version**  
Spigot 1.20.1

**Storage-type**  
MySQL

**Describe the issues**  
Players can send money to vanished players to see if they are online.
Is it possible to check if the recipient of af payment is visible to the sender?

---

**Comment by YiC200333** [comment]
What does vanished players mean? Is offline player?

**Comment by MADS0LADEN** [comment]
It is staff members not visible to normal players so they can watch if players do things against the rules

**Comment by YiC200333** [comment]
There are no plans to add this feature.

**Comment by LudovicAns** [comment]
This is very sad, you should considering this feature. I guess it's just about remove the auto completion ... Don't take it bad, you are doing a great job 🙂

**Comment by YiC200333** [comment]
OK, I will consider this feature. I will add the new permission(xconomy.staff). The player with this permission cannot accept transfers from normal players. This function may require the support of some permission plugins. (eg: luckperms)

**Comment by LudovicAns** [comment]
Blocking transactions is likely excessive. Additionally, using a permission makes the blocking permanent or context-dependent... The goal is to not give any information to "normal" players about the presence of a STAFF player in vanish mode. Therefore, either dynamically enable/disable this permission (xconomy.staff) based on whether the player is in vanish mode or not, or consider a vanished player as offline, which requires detecting if a player goes into vanish mode.

Keep in mind that the goal is to not give any clues about the online presence of a player in vanish (for example: if the /pay command has auto-completion for all players present in a server cluster, the player in vanish should not be taken into account).

**Comment by YiC200333** [comment]
OK, The staff player is in the disappearing mode by default (Every time re-enter the server, it will be restored to default). The player cannot accept transfers from normal players in the disappearing mode.

**Comment by YiC200333** [comment]
I will release the new version tomorrow

The permission is "xconomy.admin.hidden"
The command is "/xconomy hidstatus"

Players who input the command will be recognized as offline

**Comment by YiC200333** [comment]
2.25.11 added this function
