### ISSUE TITLE
文档中下载地址处 “SpigotMCGithub“ 建议换行或加个空格

### ISSUE THREAD

**Issue by postyizhan** [YiC200333/XConomy#141]
https://xc.itzdrli.com/install

![图片](https://github.com/YiC200333/XConomy/assets/97342038/3a438658-d276-4011-80f5-a295c419ced0)

**Comment by itzdrli** [comment]
https://github.com/itzdrli/XConomy-Doc/commit/2b4f8473eb32fcffdf65ff0b28747c6a33264ba6
