### ISSUE TITLE
Bungeecord Tab-Complete & Case Sensitivity

### ISSUE THREAD

**Issue by kev2k2de** [YiC200333/XConomy#17]
Hello,
is it possible to allow tab complete of players via bungeecord?
If a player wants to pay a player on another server, it can get quite annoying to type the whole name every time.

Also, is it possible to remove case sensitivity on player names?
If a player wants to pay "kev2k2" and writes it as "Kev2k2", it says that there is no such account.

Thanks :)

**Comment by YiC200333** [comment]
XConomy identifies players based on UUID, so the name must be case sensitive
Tab function feature is a little difficult, but I will try to complete it in future versions
Thank you for your feedback
