### ISSUE TITLE
2.54 Just doesnt load on Paper

### ISSUE THREAD

**Issue by dillfrescott** [YiC200333/XConomy#2]
I had to downgrade to 2.53 because it wouldn't load...

**Comment by YiC200333** [comment]
XConomy does not support the baltop function of Vault papi. I added the restriction in version 2.54, So please set 'expansions.vault.baltop.enabled' to false in the config.yml of PlaceholderAPI before upgrading.

**Comment by dillfrescott** [comment]
Ok that fixed the issue
