### ISSUE TITLE
Incompatibility with Towny command

### ISSUE THREAD

**Issue by Abwasserrohr** [YiC200333/XConomy#20]
Hi there, 

thank you for making this plugin, I really like it a lot!

Towny seems to be not able to check if the player has enough money. It can read the value of the players but if the player wants to actually deposit something into the town, it will show that there is not enough money on the account.

I think there is a method missing in https://github.com/YiC200333/XConomy/blob/master/src/main/java/me/yic/xconomy/depend/Vault.java that for example https://github.com/niccholaspage/Fe/blob/master/src/org/melonbrew/fe/VaultHandler.java has:

```
    @Override
    public boolean has(OfflinePlayer offlinePlayer, double amount) {
        return getBalance(offlinePlayer) >= amount;
    }
```

Instead of having just a string, I think Towny may use an offline player, because with the Fe plugin, it works. But I'm not really sure if that's the case.

How to recreate the incompatibility:
- Install XConomy
- Install Towny
- Install Vault
- Create a Town: /t new tmptown
- Try to deposit money: /t deposit 50
- Error should occur, even with enough money. (No error in console, just that there is not enough money)

**Comment by YiC200333** [comment]
Thanks for your feedback
You can solve this problem through setting non-player-account to true in the config.yml

**Comment by Abwasserrohr** [comment]
That worked, sorry for disturbing you.
