### ISSUE TITLE
Players with xconomy.user.balance can access other players balance

### ISSUE THREAD

**Issue by galexrt** [YiC200333/XConomy#21]
Is there a way to prevent players from accessing other players balance?

My players only have the `xconomy.user.balance` but can access other players balances.

From the Permissions list this seems as intended, but what does the `xconomy.user.balance.other` permission then?

> xconomy.user.balance - Allows player to look up the balance of yourself and others
> xconomy.user.balance.other - Allows player to look up the balance of others

**Comment by YiC200333** [comment]
If you want to prevent players from accessing other players balance, just remove `xconomy.user.balance.other` permission
eg: GroupManager
insert `- -xconomy.user.balance.other` in the related group or user

**Comment by galexrt** [comment]
Thanks that fixed it!
