### ISSUE TITLE
[Feature Request] Give someone money with a custom reason

### ISSUE THREAD

**Issue by ChibiMango** [YiC200333/XConomy#22]
I was wondering if it would be possible to add an optional argument to pay an individual with a custom message/reason using
/bal give [player] [amount] [reason]
which would override the default config message (An Administrator gave you <amount>), similar to how it works for if you want to pay everyone online using, /bal give * online [amount] [reason].

Thank you for your time!

**Comment by YiC200333** [comment]
/bal give [player] [amount] [reason]
The xconomy 2.8 and 2.9 version support this command

Thank you for feedback

**Comment by ChibiMango** [comment]
After updating to 2.9 it now let's me send a one word message thank you very much!

Am I also able to send a whole message as the string? Currently if I send something like:
**/bal give [player] 20 hi there**
it fails. I've tried using 'hi there' and "hi there" and both don't see to work.

**Comment by YiC200333** [comment]
Yes, you can modify message to 'hi_there'
I will improve this in the future version.

**Comment by YiC200333** [comment]
2.9.14 version is supported
