### ISSUE TITLE
[Suggestion] Permission or config to toggle payments

### ISSUE THREAD

**Issue by TKwSni** [YiC200333/XConomy#23]
Would it be possible to add a permission node or some config to deny players receiving money via /pay? 

I'm trying to avoid players getting pay when they  join the server for the first time until they reach some level.

**Comment by YiC200333** [comment]
yes, you can remove the permission "xconomy.user.pay" to avoid player use the pay command

**Comment by TKwSni** [comment]
Yes but that node is for the command executor, I mean when  layer1 executes "/pay player2 10" for example
 
xconomy checks if player2 has permission to  receive money, if not, then not pay. 

but if this breaks something because of offline checks of players and semi premium option, then better ignore this suggestion.

**Comment by YiC200333** [comment]
u want to have a permission to limit players to receive money from other player?

**Comment by TKwSni** [comment]
Yes

**Comment by YiC200333** [comment]
I will add this function at the next version

**Comment by YiC200333** [comment]
This function may not complete, I do not how to check the permissions of offline players at present

**Comment by YiC200333** [comment]
2.9.14 version will support this function, but it require to install Luckperms plugins
