### ISSUE TITLE
Command /eco give with too many decimals - com.mysql.jdbc.MysqlDataTruncation: Data truncation

### ISSUE THREAD

**Issue by TKwSni** [YiC200333/XConomy#25]
I get this error but it seems the amount gets sent correctly to the player

https://paste.gg/p/anonymous/9d7cccd54a354b2fa1926f03a3bbea51/files/6571912ee897447b8b8a0052a0751655/raw

it doesnt happens with /pay

**Comment by YiC200333** [comment]
Thanks, I will fix it

**Comment by YiC200333** [comment]
I tested it. But I did not find this bug

**Comment by YiC200333** [comment]
2.9.24 is fixed
