### ISSUE TITLE
对QuickShop兼容性差

### ISSUE THREAD

**Issue by jiajiaxd** [YiC200333/XConomy#26]
使用QuickShop时，提示购买成功，但是并不扣钱
1.12.2 CatServer Vault-1.6.6.jar

**Comment by YiC200333** [comment]
你QuickShop的 tax-account 设置是否正确

**Comment by jiajiaxd** [comment]
设置的是服主的ID，并且已经关闭税收功能

**Comment by jiajiaxd** [comment]
另外，XConomy为什么在MCBBS上消失了？！

**Comment by YiC200333** [comment]
我这边测试下来没有遇到问题，方便加下QQ群(mcbbs有)，详细聊下嘛？
