### ISSUE TITLE
XConomy : "message.yml"

### ISSUE THREAD

**Issue by klnknx** [YiC200333/XConomy#27]
Hello, I encounter a problem that is not necessarily a bug but remains unclear.
So, this is the first time I configure plugins etc..
And I want to customize the messages, so I go through the "message.yml" and after translating in my own way, nothing has changed.
Of course I saved, uploaded the .yml etc...
So I wanted to know if I'm the problem or the plugin.

Thank you for offering us a high quality plugin, good luck.

**Comment by YiC200333** [comment]
What version of XConomy and your server?
