### ISSUE TITLE
Currency registration

### ISSUE THREAD

**Issue by fingoltin** [YiC200333/XConomy#30]
Hey, you should register a registry module so that your currency can be accessed from Sponge.

For example, `Sponge.getRegistry().getType(Currency.class, "xconomy")` should return the currency for XConomy. This makes it possible for configurations to load your currency type.

**Comment by YiC200333** [comment]
Thanks, I will add this in the next version

**Comment by YiC200333** [comment]
df151f489cac4cc1a490c03d84189c4d53b733c4
