### ISSUE TITLE
Pay toggle feature

### ISSUE THREAD

**Issue by yunusalbayrak** [YiC200333/XConomy#32]
Hello, you should add /paytoggle for enabling & disabling getting paid by /pay command. 
Thank you.

**Comment by YiC200333** [comment]
Hi, Do you mean that the administrator gives the player /pay command permission by inputting  /paytoggle command?

**Comment by yunusalbayrak** [comment]
I mean toggling whether you are accepting payments.

**Comment by YiC200333** [comment]
#31 Similar suggestions

**Comment by YiC200333** [comment]
This function has been added in version 2.10.8
