### ISSUE TITLE
建议：希望增加目标选择器(如@p)的支持

### ISSUE THREAD

**Issue by D3CODING** [YiC200333/XConomy#33]
在命令方块中输入具体玩家名可以触发，但是@p、@r这样的选择器（如： money take @p 100）会显示“目标帐号不存在”，但系统自带的如give可以使用选择器，如果可以希望能加入相关支持！

**Comment by YiC200333** [comment]
如果你服务器版本是1.13以上的，可以通过安装插件来解决服务器无法使用@p的问题
