### ISSUE TITLE
能支持1.17吗

### ISSUE THREAD

**Issue by ghost** [YiC200333/XConomy#39]
如果1.17装上插件会显示数据库错误

**Comment by YiC200333** [comment]
可以发下报错信息吗？
还有插件版本多少

**Comment by ghost** [comment]
> 可以发下报错信息吗？
> 还有插件版本多少

![image](https://user-images.githubusercontent.com/68630033/126887842-d38028eb-15b1-452a-bd09-d7c2965e3294.png)
报错如图，就这个1.17服务端的XConomy插件出了问题，其他都无此问题
插件为最新版本：Bukkit 2.10.1 + BungeeCord

**Comment by YiC200333** [comment]
你服务器端是paper的对吗？
是的话，最新beta版本已经修复这个问题
https://1moegrzy.oss-cn-shanghai.aliyuncs.com/XConomy-Bukkit-2.10.6-Beta.jar

如果还有问题，欢迎反馈

**Comment by ghost** [comment]
> 你服务器端是paper的对吗？
> 是的话，最新beta版本已经修复这个问题
> https://1moegrzy.oss-cn-shanghai.aliyuncs.com/XConomy-Bukkit-2.10.6-Beta.jar
> 
> 如果还有问题，欢迎反馈

![image](https://user-images.githubusercontent.com/68630033/126905898-08452c6f-235e-4035-b806-76a29ed46505.png)
用了最新beta版还会出现这个报错，配置无改动，服务端是Airplane 1.17，基于Paper 1.17，另外关闭服务器时也出现了一个报错
![image](https://user-images.githubusercontent.com/68630033/126905922-bfc6081d-bb21-4926-8e4a-edacc76370aa.png)

**Comment by YiC200333** [comment]
你database.yml中时区设置不正确
