### ISSUE TITLE
转账问题

### ISSUE THREAD

**Issue by HmQaq** [YiC200333/XConomy#40]
从A服转账给B服玩家金钱,B服玩家金钱不会刷新，也没有收到收钱的提示，需要跳转到A服才有金钱(但是在B服的时候金钱排行榜显示自己有转账后的金钱),MYSQL设置应该没有问题，

**Comment by HmQaq** [comment]
A服

**Comment by YiC200333** [comment]
你BungeeCord端有安装插件吗？
