### ISSUE TITLE
同步问题

### ISSUE THREAD

**Issue by zfms4188** [YiC200333/XConomy#41]
也不是很清楚触发原因,早上开启后,玩家仅有几十人,这时A,B,C,等等服务器的金币同步没有任何问题.
在临近晚上时,服务器大概200多人左右时,同步突然就失效了,具体就是,A服购买物品后,去到B,C服等等金币并没有消耗,反之亦然.
期间服务器并没有重启,后台并无报错.
服务器版本为1.7

**Comment by YiC200333** [comment]
好的，多谢反馈，可以告诉下您插件的版本吗？
如果可以的话，选几个出问题玩家的名称发送给我吗？
我进行测试，谢谢

**Comment by zfms4188** [comment]
我用的是最新版本,
在我开启了缓存功能后,好像就没出现这个问题了
(没看见玩家给我反应)
这个问题也不太好测试,因为我也不知道出现的原因 (

**Comment by zfms4188** [comment]
对了 这里聊不方便
我已经加了bbs下的讨论群了
你还没有通过 （
