### ISSUE TITLE
Users balance when they do /bal is different than their actual balance

### ISSUE THREAD

**Issue by ghost** [YiC200333/XConomy#44]
When new users, and users who change their names do /bal it says they have 0 dollars. BUT when we do /bal {playername} it says they have money. And no its not a visual bug, they cant do /pay or do anything that requires money. They all have money in their balance. here's my config, and yes im using bungeecord

`Settings:
  language: English
  check-update: true
  refresh-time: 300
  eco-command: true
  disable-essentials: true
  initial-bal: 600
  ranking-size: 10
  non-player-account: false
  cache-correction: false
  transaction-record: true
  semi-online-mode: true
  username-ignore-case: false
  lines-per-page: 5
Currency:
  singular-name: dollar
  plural-name: dollars
  integer-bal: false
  thousands-separator: ','
  display-format: '%balance% %currencyname%'
  max-number: '10000000000000000'
BungeeCord:
  enable: true
  sign: aa
`

**Comment by YiC200333** [comment]
Thanks for your feedback. I will fix it

**Comment by YiC200333** [comment]
https://1moegrzy.oss-cn-shanghai.aliyuncs.com/XConomy-Bukkit-2.11.1.jar
I fix this problem in this version, try it and welcome feedback.
BungeeCord and all server require to update version.
