### ISSUE TITLE
Relocate org.slf4j.impl

### ISSUE THREAD

**Issue by A248** [YiC200333/XConomy#46]
The jar (at least the one I downloaded from SpigotMC) contains the `org.slf4j.impl` package from Slf4j.

XConomy should relocate this dependency so as to avoid conflicts between it, other plugins, and possibly the server (many server versions include slf4j themselves).

**Comment by YiC200333** [comment]
I am also looking for a solution now. If I relocate, an error will be reported on the server of paper1.17.1 server

**Comment by YiC200333** [comment]
2.11.3 version is fixed
