### ISSUE TITLE
enhancement request: display received money on reconnect

### ISSUE THREAD

**Issue by Uharn** [YiC200333/XConomy#48]
/pay <offline player> works, but the player has no information taht he received money while offline
Is there a possibility to add some messages when player connecte that list the money received while offline?
or maybe a command for the player to list it's own balance history as it's in the db?

**Comment by YiC200333** [comment]
OK, I will add this function in the future version. But there are other functions that need to be added. It will be later

**Comment by YiC200333** [comment]
2.17.2 version added this function
