### ISSUE TITLE
NPC Eco Accounts

### ISSUE THREAD

**Issue by Tstorm89** [YiC200333/XConomy#5]
I'm running a server with Towny and have found that money deposited into town banks will disappear upon reloading a server. 

Within /Xconomy/playerdata/data.yml, the correct balance is listed and updated. However, within /Xconomy/playerdata/datanon.yml, the account is listed, but sits at a value of 0.0. This appears to be the value that Towny reads. I can change it manually (which is pointless, though it works), but it will not update on its own.

**Comment by YiC200333** [comment]
Sorry, this is bug, it has been fixed in the latest version 2.5.11.

**Comment by Tstorm89** [comment]
Excellent! Glad to hear that & love the work you've done!
