### ISSUE TITLE
Question about bungee sync: I have an Auction House plugin, what will happen if the player sells something while offline?

### ISSUE THREAD

**Issue by j-lorenzo** [YiC200333/XConomy#52]
Question about bungee sync: I have an Auction House plugin, what will happen if the player sells something while offline?

![image](https://user-images.githubusercontent.com/16794234/147564809-04a64e3c-28c9-46e5-b68c-b2e9c80110f8.png)

On the other hand, what features does the fact that it has bungee compatibility provide? When writing to database it should apply when changing server, right?

Thank you :)

**Comment by YiC200333** [comment]
If the player sells something while offline when enable BC mode, XConomy will return `EconomyResponse.ResponseType.FAILURE`, like insufficient balance

**Comment by YiC200333** [comment]
Or disable caching, you can ignore this
