### ISSUE TITLE
Balanace others permission problem 

### ISSUE THREAD

**Issue by ghost** [YiC200333/XConomy#58]
Hello,
im using luckperms and have default group, deny *
So all permission should be set to false unless I set a specific permission to true. 

Then i set the XConemy permission i wanted my players to be able to use.
xconomy.user.pay.receive | true
xconomy.user.pay | true
xconomy.user.balancetop | true
xconomy.user.balance | true

Now i thought the player can't use /balance <player>
But yes they can. 

I had to set the permission "xconomy.user.balance.other" to false. Problem solved.
Is this normal? On other plugins there is no such behavior atleast not at my knowledge

**Comment by YiC200333** [comment]
Yes, it is normal. because 'xconomy.user.balance.other' is 'xconomy.user.balance' 's child permission. if you give player 'xconomy.user.balance' permision. it is including 'xconomy.user.balance.other'
