### ISSUE TITLE
There is a bug when I use QuickShop and XConomy

### ISSUE THREAD

**Issue by kevinwang-0916** [YiC200333/XConomy#59]
Players will get double the amount for buying their own item account

https://github.com/PotatoCraft-Studio/QuickShop-Reremake/issues/155

**Comment by YiC200333** [comment]
What version of XConomy?
Are there any other economic plugins or bc synchronization plugins in your server?

**Comment by kevinwang-0916** [comment]
The latest version of XConomy
No other economic plugins or bc synchronization plugins in my server!

伊C ***@***.***>) 在 2022年5月9日星期一寫道：

**Comment by YiC200333** [comment]
Can you upload you XConomy's config.yml

**Comment by kevinwang-0916** [comment]
Yes, I will.
https://paste.gg/p/anonymous/f4a0e0619be04641abf41f4faf05e661

**Comment by YiC200333** [comment]
can u upload your MysqlPlayerDataBridge's config?

**Comment by kevinwang-0916** [comment]
I have tried without installing MysqlPlayerDataBridge but the problem still occurs
So it shouldn't be a problem with MysqlPlayerDataBridge

**Comment by YiC200333** [comment]
Can you create a test server and just keep the xconomy and quickshop plugins, Check if the problem still exists?
I tested it, do not have this problem

**Comment by kevinwang-0916** [comment]
I only have Vault and xconomy and quickshop installed
But the problem still occurs.

But plugins doesn't work without the Vault installed.

**Comment by kevinwang-0916** [comment]
I have tried to use the original configuration of xconomy (no MySQL no BungeeCord sync)
The plugin will work fine
Want to ask if I have any configuration errors?

**Comment by YiC200333** [comment]
Thanks for your feedback, I found this problem.
you can set disenable-cache to false to solve this problem

**Comment by YiC200333** [comment]
The problem is fixed in 2.18.2 version

**Comment by kevinwang-0916** [comment]
Thank you for your positive reply!

**Comment by kevinwang-0916** [comment]
Yes, I will.

伊C ***@***.***> 於 2022年5月9日 週一 下午10:19寫道：
