### ISSUE TITLE
Sponge - Permission Issue / Suggestion

### ISSUE THREAD

**Issue by Aiidoneus** [YiC200333/XConomy#63]
**Version of XConomy**  
XConomy-Sponge-2.18.3

**Server version**  
spongeforge-1.12.2-2838-7.4.7

**Storage-type**  
Local

**Describe the issues**  
Hello, right now, there seems to be issues with permissions that I will help explain. Sponge uses a more wildcard system as you can see **_[here](https://docs.spongepowered.org/stable/en/plugin/permissions.html)_**. The issue with this is that people who have say `xconomy.user.balance` also automatically get `xconomy.user.balance.other` along with it unless you specifically deny it to said Luckperms group. This can also happen with `xconomy.user.pay` and `xconomy.user.pay.receive` for example. My suggestion is to rename the permissions slightly so this doesn't happen. Maybe something like `xconomy.user.pay.base` and keep xconomy.user.pay.receive` to split them up properly? Ultimately this is up to you but it is just a suggestion

**Comment by YiC200333** [comment]
Thanks for you help and suggestion, I will try it
