### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by YangMu0987** [YiC200333/XConomy#64]
**Version of XConomy**  
XConomy V2.0.0

**Server version**  
Spigot 1.17.1

**Storage-type**  
SQLite / MySQL

**Describe the issues**  
Issues
An internal error occurred while attempting to perform this command
else:This server have CMI
---

**(option)XConomy's config.yml**

**(option)Screenshots**

**Comment by YiC200333** [comment]
set money bal balance pay baltop command to false in CMI / Alias
