### ISSUE TITLE
Economy#format returns just the plain number

### ISSUE THREAD

**Issue by adamtomi** [YiC200333/XConomy#7]
It'd be pretty neat, if XConomy's vault hook would format balances (returned by `Economy#format`) using the formatter that can be customized in the config file. (`display-format: '%balance% %currencyname%'`)

I'll happily open a PR if you'd like.

**Comment by YiC200333** [comment]
OK, I will change it in the next version

**Comment by adamtomi** [comment]
Thank you!

**Comment by YiC200333** [comment]
2.7.14 version is modified

**Comment by adamtomi** [comment]
Thanks
