### ISSUE TITLE
[API]changePlayerBalance时发生的 java.lang.NullPointerException

### ISSUE THREAD

**Issue by moxisuki** [YiC200333/XConomy#71]
**Version of XConomy**  
XConomy-Bukkit-2.18.14

**Server version**  
Purpur-1.18.2-1632

**Storage-type**  
SQLite 

**Describe the issues**  
at this
https://github.com/YiC200333/XConomyAPI/issues/2

---

**(option)XConomy's config.yml**
default
**(option)Screenshots**
default

**Comment by YiC200333** [comment]
谢谢反馈，已经修复
