### ISSUE TITLE
Feature request: toggle check my balance by other people

### ISSUE THREAD

**Issue by Cr4zyGeek** [YiC200333/XConomy#72]
**Version of XConomy**  
XConomy V2.19.2

**Server version**  
Spigot 1.17.1

**Storage-type**  
SQLite / MySQL

**Describe the issues**  
+ Add the possibility to toggle if others can check my personnal balance with the `balance/money <player>` command
+ If I toggle off the possibility for others to check my personnal balance then my balance will not be display in the `balancetop` command and by the `%xconomy_top_player_#%` + `%xconomy_top_balance_#%` + `%xconomy_top_balance_value_#%` placeholders
+ Add in config the possibility to force the "private" balances to be display by the `balancetop` command and by the placeholders

**Comment by YiC200333** [comment]
These functions are not considered at present
