### ISSUE TITLE
Feature request: placeholders in message.yml

### ISSUE THREAD

**Issue by Cr4zyGeek** [YiC200333/XConomy#73]
**Version of XConomy**  
XConomy V2.19.2

**Server version**  
Spigot 1.17.1

**Storage-type**  
SQLite / MySQL

**Describe the issues**  
+ Add the possibility to configure in the message.yml what the placeholders display, for example when they have no data to display

**Comment by YiC200333** [comment]
I will add this function in the future version

**Comment by YiC200333** [comment]
2.19.5 version add this funtion
