### ISSUE TITLE
Console spam on SpongeForge

### ISSUE THREAD

**Issue by ahdg6** [YiC200333/XConomy#75]
**Version of XConomy**  
XConomy V2.19.2

**Server version**  
Sponge-1.12.2-2838-7.4.8-RC4141 (API 7)

**Storage-type**  
SQLite

**Describe the issues**  
Console Spam, check details below
<details>
[21:22:09] [pool-2-thread-4/ERROR] [Sponge]: The Scheduler tried to run the task xconomy-A-2553 owned by Plugin{id=xconomy, name=XConomy, version=2.19.2-Sponge7, url=https://ore.spongepowered.org/YiC/XConomy, authors=[YiC], source=.\mods\_XConomy-Sponge7-2.19.2.jar}, but an error occured.
java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=pool-2-thread-4, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
> 	at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:121) ~[SpongeCauseStackManager.class:1.12.2-2838-7.4.8-RC4141]
> 	at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:136) ~[SpongeCauseStackManager.class:1.12.2-2838-7.4.8-RC4141]
> 	at net.minecraft.entity.player.EntityPlayerMP.bridge$kick(EntityPlayerMP.java:5699) ~[oq.class:?]
> 	at net.minecraft.entity.player.EntityPlayerMP.kick(EntityPlayerMP.java:3408) ~[oq.class:?]
> 	at me.yic.xconomy.adapter.comp.CPlayer.lambda$kickPlayer$0(CPlayer.java:43) ~[CPlayer.class:?]
> 	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.4.8-RC4141]
> 	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.4.8-RC4141]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_332]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_332]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_332]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_332]
> 	at java.lang.Thread.run(Thread.java:855) [?:1.8.0_332]
> 
</details>

**Comment by ahdg6** [comment]
V2.18.11 works fine.

**Comment by YiC200333** [comment]
Does the error has any other information?

**Comment by ahdg6** [comment]
It just happens on v2.19.2 with default settings.  Also, no error on v2.18.14
Log: https://paste.ee/p/aROlZ

**Comment by YiC200333** [comment]
Can u send me your config.yml

**Comment by ahdg6** [comment]
Sure, here is config.yml: https://paste.ee/p/x2VNG
I use same config on both of versions. For now, I use v.2.18.4 on my production env.

**Comment by YiC200333** [comment]
try this version 
https://1moegrzy.oss-cn-shanghai.aliyuncs.com/XConomy-Sponge7-2.19.3.jar
