### ISSUE TITLE
add Treasury support.

### ISSUE THREAD

**Issue by BearLeonLight** [YiC200333/XConomy#76]
**Version of XConomy**  
XConomy V2.19.5

**Server version**  
Spigot 1.19.2

**Storage-type**  
MySQL

**Describe the issues**  
Can we add Treasury support.
https://github.com/lokka30/Treasury/wiki/About-Treasury
---

**(option)XConomy's config.yml**

**(option)Screenshots**

**Comment by YiC200333** [comment]
I will add Non-player account's default support
