### ISSUE TITLE
xconomy just repeats the commands I say in chat

### ISSUE THREAD

**Issue by Superior126** [YiC200333/XConomy#81]
**Version of XConomy**  
XConomy V2.19.5

**Server version**  
Spigot 1.8.8

**Storage-type**  
MySQL

**Describe the issues**  
1. xconomy just repeats the commands I say in chat. fir example if I type /balance, it just spits out /balance in the chat
2. every no and then I will get kicked from being disconnected from proxy ever since installing this plugin

---

**Comment by YiC200333** [comment]
I tested on the 1.8.8 server. No problem found. Do you have any other conflicting plugins
