### ISSUE TITLE
Some features request

### ISSUE THREAD

**Issue by Yavoroshko** [YiC200333/XConomy#82]
First of all, your plugin is awesome. Especially, tax for transfers, currency naming. 
It would be great if you add hex support for messages and one more currency support for example the donator one.

Oh and I have noticed that if player send 0.01 or 0.02 coins taxes not applying.. also there is no option to set minimum value to send, for example player can sent only value that at least 10.

And also if will be really useful to have an option to use only integers numbers

So
- HEX
- Donator currency
- Minimum funds to send
- Only integers numbers option

**Comment by YiC200333** [comment]
Thank you for your feedback

XConomy support HEX code and has integers numbers option(Currency.integer-bal). 
I will consider adding the function minimum funds to send in future versions.
XConomy does not consider add multi-currency function.
