### ISSUE TITLE
Not working for spongeforge API8

### ISSUE THREAD

**Issue by ManOfKott** [YiC200333/XConomy#83]
**Version of XConomy**  
XConomy V2.19.5-Sponge8

**Server version**  
SpongeForge 1.16.5

**Storage-type**  
SQLite / MySQL

**Describe the issues**  
The plugin is not loading on my server. I dont know if the plugin only works for spongevanilla or if there is a special way of installing the plugin

---

**(option)XConomy's config.yml**

**(option)Screenshots**

**Comment by YiC200333** [comment]
I tested in my test server. it is no problem. (spongevanilla-1.16.5-8.1.0-RC1264-universal)
Does the console display any information?
