### ISSUE TITLE
question about the baltop command

### ISSUE THREAD

**Issue by Zarkness2** [YiC200333/XConomy#88]
Does the /baltop command only show the top 10 people with the most money or does it show the top from 1 to infinity?

For example if I get 5000 users in 1 year, if I set /baltop 50 it will show me the people who are more than the top 10.

That is something that has the essentials and I like that you can go looking at the money of all the people who entered the server.

**Comment by YiC200333** [comment]
You can set this in config.yml

**Comment by Zarkness2** [comment]
okey thanks

**Comment by Zarkness2** [comment]
the option you say is the one in the image? if it is that would be possible to put that has no limit is that I do not want to have a maximum limit of 100, I want to be able to put that they can see infinitely, if I enter a total of 4000 people in 2 years so they can see the money they have those 4000 people in the top and that will increase as they enter new users 
![image](https://user-images.githubusercontent.com/48263644/233031511-59b118db-88db-477d-8496-13324e103a83.png)
@YiC200333

**Comment by YiC200333** [comment]
Without the infinite option, infinite ranking will increase the pressure on the database

**Comment by Zarkness2** [comment]
> Without the infinite option, infinite ranking will increase the pressure on the database

that is not a problem in my case, it is more for taste, so I can put either by custom menu, or with the plugin itself by chat to see the top to where it exists, if the current limit is 50 then look at the top to 50, if in the future the limit of the top is 10000 then look at the 10000

**Comment by YiC200333** [comment]
OK, I will add option contact restrictions in the next version

**Comment by Zarkness2** [comment]
thanks

**Comment by YiC200333** [comment]
But XConomy's Ranking adopts a caching mechanism. If you set it to infinite in config, it will be read all data from MySQL periodically

**Comment by YiC200333** [comment]
So you can't restrict him through buttons

**Comment by Zarkness2** [comment]
okey
