### ISSUE TITLE
[Request] Will it possible to add Folia support?

### ISSUE THREAD

**Issue by Aitooor** [YiC200333/XConomy#91]
**Version of XConomy**  
XConomy V2.0.0

**Server version**  
Folia 1.19.4
Folia link: https://github.com/PaperMC/Folia

**Storage-type**  
SQLite / MySQL
Both, better MySQL

**Comment by Aitooor** [comment]
Will it possible?

**Comment by YiC200333** [comment]
I haven't had time recently, so I can't give a definite answer at the moment

**Comment by Aitooor** [comment]
> I haven't had time recently, so I can't give a definite answer at the moment

Okaay, thanks for your time. No problem 😄
