### ISSUE TITLE
 Error occurred while enabling XConomy v2.22.1 (Is it up to date?)

### ISSUE THREAD

**Issue by dimaevseenko** [YiC200333/XConomy#94]
**Version of XConomy**  
XConomy V2.22.1

**Server version**  
Spigot 1.12.2

**Storage-type**  
SQLite / MySQL

**Describe the issues**  
Issues
![image](https://github.com/YiC200333/XConomy/assets/11544700/69555e22-2252-41f6-a4bf-52df42ffa336)

**Comment by YiC200333** [comment]
XConomy does not support mohist

**Comment by dimaevseenko** [comment]
Magma also?

**Comment by YiC200333** [comment]
I am not sure, I did not test in the Magma.
But this error is the same as mohist
