### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by Vennntox** [YiC200333/XConomy#96]
**Version of XConomy**  
XConomy V2.22.1

**Server version**  
Spigot 1.8.8

**Storage-type**  
SQLite / MySQL

**Describe the issues**  
Placeholder %xconomy_top_rank_{number}%
not working

![enanntdsa](https://github.com/YiC200333/XConomy/assets/31446572/fd399c22-0d07-49e0-a2f9-fa304218c678)

---

**(option)XConomy's config.yml**

**(option)Screenshots**

**Comment by YiC200333** [comment]
How many player data do you currently have?

**Comment by Vennntox** [comment]
i have 2

**Comment by YiC200333** [comment]
Because there is not enough data, NODATA is displayed

**Comment by Vennntox** [comment]
okay, that's not what I mean "1 - Vennt0x" and the 2nd place "Out of Top10 - B4wn" the number 2 doesn't work

**Comment by YiC200333** [comment]
%xconomy_top_rank% is used to query the current player's ranking
%xconomy_top_rank_#%# should be player name, to query the # player's ranking
