### ISSUE TITLE
请支持Folia服务端

### ISSUE THREAD

**Issue by LoliColleen** [YiC200333/XConomy#97]
目前已经有部分插件支持Folia服务端了，希望XConomy也能支持Folia服务端
目前支持Folia的插件: https://github.com/BlockhostOfficial/folia-plugins
Folia的github: https://github.com/PaperMC/Folia
顺便，resources/plugin.yml需要加一条folia-supported: true

**Comment by YiC200333** [comment]
好的，有计划制作

**Comment by YiC200333** [comment]
2.24.4已支持
