### ISSUE TITLE
1.20 You know..

### ISSUE THREAD

**Issue by 164ebr** [YiC200333/XConomy#99]
**Version of XConomy**  
XConomy V2.22.1

**Server version**  
Paper 1.20

**Storage-type**  
SQLite

**Describe the issues**  
1.20 support..

---

**(option)XConomy's config.yml**
none
**(option)Screenshots**
![image](https://github.com/YiC200333/XConomy/assets/86980013/dbf1c549-3104-4c1e-8094-f11bb10328ab)

**Comment by YiC200333** [comment]
We haven't had time recently, we will test it next month
